server:
  port: 9527

spring:
  application:
    name: cloud-zuul-9527

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: cloud-zuul-9527


zuul:
  routes:
    prov:
      serviceId: cloud-provider-student
      path: /stu/**
  ignored-services: "*"  #不能使用此路径访问